# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/dialog_config_raw.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(466, 406)
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.dateEdit_inicio = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_inicio.setCalendarPopup(True)
        self.dateEdit_inicio.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_inicio.setObjectName("dateEdit_inicio")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_inicio)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dateEdit_fim = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_fim.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.dateEdit_fim.setCalendarPopup(True)
        self.dateEdit_fim.setObjectName("dateEdit_fim")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_fim)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_adicionar_feriado = QtWidgets.QPushButton(self.groupBox)
        self.button_adicionar_feriado.setFlat(False)
        self.button_adicionar_feriado.setObjectName("button_adicionar_feriado")
        self.horizontalLayout.addWidget(self.button_adicionar_feriado)
        self.button_remover_feriado = QtWidgets.QPushButton(self.groupBox)
        self.button_remover_feriado.setObjectName("button_remover_feriado")
        self.horizontalLayout.addWidget(self.button_remover_feriado)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.listWidget_feriados = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_feriados.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget_feriados.setAlternatingRowColors(True)
        self.listWidget_feriados.setObjectName("listWidget_feriados")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.listWidget_feriados)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_usuario = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_usuario.setObjectName("lineEdit_usuario")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_usuario)
        self.lineEdit_senha = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_senha.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_senha.setInputMask("")
        self.lineEdit_senha.setText("")
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_senha.setClearButtonEnabled(False)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_senha)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Configurações gerais"))
        self.label.setText(_translate("Dialog", "Data de início do semestre"))
        self.dateEdit_inicio.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.label_2.setText(_translate("Dialog", "Data de término do semestre"))
        self.dateEdit_fim.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.groupBox.setTitle(_translate("Dialog", "Feriados"))
        self.button_adicionar_feriado.setText(_translate("Dialog", "Adicionar"))
        self.button_remover_feriado.setText(_translate("Dialog", "Remover"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Semestre"))
        self.label_3.setText(_translate("Dialog", "Usuário"))
        self.label_4.setText(_translate("Dialog", "Senha"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Autenticação"))

